# This is a basic workflow that is manually triggered

name: Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      set_release:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Select OS Release.'
        # Default value if no value is explicitly provided
        default: 'jammy'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: choice
        options:
          - jammy
          - noble
          - bullseye
          - bookworm

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Initialize the environment
      run: |
        echo "Hello ${{ inputs.set_release }}"
        sudo apt install --quiet gcc gcc-aarch64-linux-gnu bc bison build-essential coccinelle \
          device-tree-compiler dfu-util efitools flex gdisk graphviz imagemagick \
          liblz4-tool libgnutls28-dev libguestfs-tools libncurses-dev \
          libpython3-dev libsdl2-dev libssl-dev lz4 lzma lzma-alone openssl \
          pkg-config python3 python3-asteval python3-coverage python3-filelock \
          python3-pkg-resources python3-pycryptodome python3-pyelftools \
          python3-pytest python3-pytest-xdist python3-sphinxcontrib.apidoc \
          python3-sphinx-rtd-theme python3-subunit python3-testtools \
          python3-virtualenv swig uuid-dev
        echo "current directory:" `pwd`
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make CROSS_COMPILE=aarch64-linux-gnu- KBUILD_OUTPUT=out p212_M17_defconfig -j4
        make CROSS_COMPILE=aarch64-linux-gnu- KBUILD_OUTPUT=out -j4
        echo "output files:" `ls out/`
    - name: Release
      uses: ncipollo/release-action@main
      with:
        tag: v1
        artifacts: out/u-boot.bin out/u-boot.dtb
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
